#pragma checksum "c:\Users\miste\source\repos\BlazorComponentGenerator\ComponentLibrary\Component1.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a9642925b3c4f4ee2c5da74edbb10f7229514b9cdf4908ba762912e81247f786"
// <auto-generated/>
#pragma warning disable 1591
namespace ComponentLibrary
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "c:\Users\miste\source\repos\BlazorComponentGenerator\ComponentLibrary\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
    public partial class Component1 : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h3>Component1 unmodified</h3>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
