#pragma checksum "c:\Users\miste\source\repos\BlazorComponentGenerator\ComponentLibrary\Component2.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "d44659c00ccb13c3fe7cb270b38de64ba28966182e4956648bdb21b4f205fd83"
// <auto-generated/>
#pragma warning disable 1591
namespace ComponentLibrary
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "c:\Users\miste\source\repos\BlazorComponentGenerator\ComponentLibrary\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
    public partial class Component2 : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h3>Component2 unmodified</h3>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
